sudo: false
language: python
python:
  - "3.6"

before_script:
  - echo $PATH
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.3/lib/python3.6/bin
  - export CHROME_BIN=chromium-browser
install: pip install tox-travis
script: tox
