from selenium.webdriver.common.by import By

class SupplierPageLocators(object):

    signin = (By.CLASS_NAME, 'btn-primary')
    kirv_logo = (By.XPATH, '//img[@alt = "KIRV"]')
    products_link = (By.XPATH, '//*[@id = "main-navigation"]/ul/li[1]')
    customers_link = (By.XPATH, '//*[@id = "main-navigation"]/ul/li[2]')
    orders_link = (By.XPATH, '//*[@id = "main-navigation"]/ul/li[3]')
    input_search_customers = (By.XPATH, '//input[@placeholder="Search Customers"]')
    search_button = (By.XPATH, '//button[text() = "Search"]')
    logout_button = (By.XPATH, '//span[text() = "Logout"]')
    customers_title = (By.CLASS_NAME, 'page-title')
    all_customer_link = (By.XPATH, '//a[text()="All Customers"]//parent::li')
    pending_link = (By.XPATH, '//a[text()="Pending"]//parent::li')
    active_link = (By.XPATH, '//a[text()="Active"]//parent::li')
    inactive_link = (By.XPATH, '//a[text()="Inactive"]//parent::li')
    customer_name = (By.XPATH, '//th[text()="CUSTOMER NAME"]')
    state = (By.XPATH, '//th[text()="STATE"]')
    no_of_locations = (By.XPATH, '//th[text()="NO. OF LOCATION"]')
    main_contact = (By.XPATH, '//th[text()="MAIN CONTACT"]')
    phone_number = (By.XPATH, '//th[text()="PHONE NUMBER"]')
    account_status = (By.XPATH, '//th[text()="ACCOUNT STATUS"]')
    table_body = (By.XPATH, 'html/body/table/tbody')
    table_rows = (By.XPATH, '//tr')
    table_data = (By.XPATH, '//td')
    total_table_records = (By.XPATH, '//quick-filter/div/div[2]/div')
    page_number1 = (By.XPATH, '//a[text()="1"]//parent::li')
    page_number2 = (By.XPATH, '//a[text()="2"]//parent::li')
    page_link = (By.CLASS_NAME, 'page-link')
    search_message = (By.XPATH, '//h3[text()="Contracts Not Found!"]')
    first_record_customer_name = (By.XPATH, '//table/tbody/tr/td[1]')
    first_record_state = (By.XPATH, '//table/tbody/tr/td[2]')
    first_record_no_of_location = (By.XPATH, '//table/tbody/tr/td[3]')
    first_record_main_contact = (By.XPATH, '//table/tbody/tr/td[4]')
    first_record_phone_number = (By.XPATH, '//table/tbody/tr/td[5]')
    first_record_account_status = (By.XPATH, '//table/tbody/tr/td[6]')
    view = (By.XPATH, '//table/tbody/tr/td[7]')
    edit_company_information = (By.XPATH, '//fieldset//span[text()="Edit"]')
    company_name_input = (By.XPATH, '//fieldset//input')
    company_address_input = (By.XPATH, '//fieldset//input[2]')
    company_city_input = (By.XPATH, '//fieldset//input[3]')
    company_state_input = (By.XPATH, '//fieldset//input[4]')
    company_post_code_input = (By.XPATH, '//fieldset//input[5]')
    company_reseller_id_input = (By.XPATH, '//fieldset//input[7]')
    company_account_no_input = (By.XPATH, '//fieldset//input[8]')
    company_phone_input = (By.XPATH, '//fieldset//input[9]')
    company_other_phone_input = (By.XPATH, '//fieldset//input[10]')
    company_email_input = (By.XPATH, '//fieldset//input[11]')
    company_website_input = (By.XPATH, '//fieldset//input[12]')
    company_cancel_button = (By.XPATH, '//fieldset//button[text()="Cancel"]')
    company_save_button = (By.XPATH, '//fieldset//button[text()="Save"]')
    edit_contact_information = (By.XPATH, '//fieldset[2]//span[text()="Edit"]')
    contact_name_input = (By.XPATH, '//fieldset[2]//input')
    contact_phone_input = (By.XPATH, '//fieldset[2]//input[2]')
    contact_email_input = (By.XPATH, '//fieldset[2]//input[3]')
    contact_cancel_button = (By.XPATH, '//fieldset[2]//button[text()="Cancel"]')
    contact_save_button = (By.XPATH, '//fieldset[2]//button[text()="Save"]')
    edit_location_information = (By.XPATH, '//fieldset[3]//span[text()="Edit"]')
    location_name1_input = (By.XPATH, '//fieldset[3]//input')
    location_adddress1_input = (By.XPATH, '//fieldset[3]//input[2]')
    location_city1_input = (By.XPATH, '//fieldset[3]//input[3]')
    location_state1_input = (By.XPATH, '//fieldset[3]//input[4]')
    location_post_code1_input = (By.XPATH, '//fieldset[3]//input[5]')
    location_email1_input = (By.XPATH, '//fieldset[3]//input[7]')
    location_phone1_input = (By.XPATH, '//fieldset[3]//input[8]')
    location_name2_input = (By.XPATH, '//fieldset[3]//input[9]')
    location_adddress2_input = (By.XPATH, '//fieldset[3]//input[10]')
    location_city2_input = (By.XPATH, '//fieldset[3]//input[11]')
    location_state2_input = (By.XPATH, '//fieldset[3]//input[12]')
    location_post_code2_input = (By.XPATH, '//fieldset[3]//input[13]')
    location_email2_input = (By.XPATH, '//fieldset[3]//input[15]')
    location_phone2_input = (By.XPATH, '//fieldset[3]//input[16]')
    location_cancel_button = (By.XPATH, '//fieldset[3]//button[text()="Cancel"]')
    location_save_button = (By.XPATH, '//fieldset[3]//button[text()="Save"]')
    edit_ship_information = (By.XPATH, '//fieldset[4]//span[text()="Edit"]')
    ship_name1_input = (By.XPATH, '//fieldset[4]//input')
    ship_adddress1_input = (By.XPATH, '//fieldset[4]//input[2]')
    ship_city1_input = (By.XPATH, '//fieldset[4]//input[3]')
    ship_state1_input = (By.XPATH, '//fieldset[4]//input[4]')
    ship_post_code1_input = (By.XPATH, '//fieldset[4]//input[5]')
    ship_email1_input = (By.XPATH, '//fieldset[4]//input[7]')
    ship_phone1_input = (By.XPATH, '//fieldset[4]//input[8]')
    ship_start_time1_input = (By.XPATH, '//fieldset[4]//input[9]')
    ship_end_time1_input = (By.XPATH, '//fieldset[4]//input[10]')
    ship_name2_input = (By.XPATH, '//fieldset[4]//input[11]')
    ship_adddress2_input = (By.XPATH, '//fieldset[4]//input[12]')
    ship_city2_input = (By.XPATH, '//fieldset[4]//input[13]')
    ship_state2_input = (By.XPATH, '//fieldset[4]//input[14]')
    ship_post_code2_input = (By.XPATH, '//fieldset[4]//input[15]')
    ship_email2_input = (By.XPATH, '//fieldset[4]//input[17]')
    ship_phone2_input = (By.XPATH, '//fieldset[4]//input[18]')
    ship_start_time2_input = (By.XPATH, '//fieldset[4]//input[19]')
    ship_end_time2_input = (By.XPATH, '//fieldset[4]//input[20]')
    ship_cancel_button = (By.XPATH, '//fieldset[4]//button[text()="Cancel"]')
    ship_save_button = (By.XPATH, '//fieldset[4]//button[text()="Save"]')
